#!/bin/bash
# Set your desired username here
USERNAME=arch

# Will need to bootstrap from external device first: 
# mount [target-partition] /mnt
# mount [efi-partition] /mnt/esp
# pacstrap /mnt base linux linux-firmware
# arch-chroot /mnt
pacman -S base linux linux-firmware wpa_supplicant gvim tmux iproute2 dhcpcd grub efibootmgr xorg kde-applications plasma tlp xclip os-prober git sudo xorg-xinit xterm zsh fzf ripgrep gcc make cmake flake8 python-pip ctags autopep8 rustfmt clang base-devel docker docker-compose wireguard-tools

grub-install --target=x86_64-efi --efi-directory=/esp --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime

# Create user
useradd -m -G wheel -s /bin/bash $USERNAME
passwd $USER
su $USER

# Set up oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Set up vim
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
sudo -H pip3 install pynvim

# Set up tmux
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
curl https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux | sudo tee -a /usr/share/bash-completion/completions/tmux

# Install yay for AUR management
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

# Edit /etc/locale.gen, then run locale-gen
# Edit /etc/hostname
# Edit /etc/hosts
# Set passwd
# Edit /etc/sudoers to give wheel group sudo rights


# open GUI
# startx /usr/bin/startplasma-x11
