#!/bin/bash
set -e

which curl > /dev/null 2>&1 || echo "Please install curl"

cd `git rev-parse --show-toplevel`

cp _* $HOME
cd $HOME; for file in _*; do mv $file ${file//_/.}; done

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash                 # For plugins with node dependencies

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install --lts
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim        # vim-plug

git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm 
curl https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux | sudo tee -a /usr/share/bash-completion/completions/tmux

which apt && sudo apt update && sudo apt install fzf ripgrep 
which pacman && sudo pacman -Syu && sudo pacman -S fzf ripgrep 

