#!/bin/bash

# https://discuss.linuxcontainers.org/t/gui-apps-in-lxd-container/4612/3
# check that you have something like ubuntu:1000:65536 in /etc/sub[g|u]id

sudo lxd init

#Manual setup
#lxc launch ubuntu:20.04 ubuntu
#lxc config device add ubuntu workspaces disk path=/home/ubuntu/workspaces source="/home/ubuntu/workspaces"

# Add this to lxc profile create guil lxc profile add ubuntu gui; lxc profile edit gui
# Check that /tmp/.X11/unix/X0 exists ( echo $DISPLAY on host )
# other wise modify X0 below
:'
config:
  environment.DISPLAY: :0
  raw.idmap: both 1000 1000
description: Enables graphical apps use.
devices:
  X0:
    path: /tmp/.X11-unix/X0
    source: /tmp/.X11-unix/X0
    type: disk
  mygpu:
    type: gpu
name: gui
used_by: []
'

# Make sure in /etc/avahi/avahi-daemon.conf, cache-entries-max=4096
