#!/bin/bash
set -e

forward_network_interfaces() {
  echo "Forwards packets between two network interfaces, making this device act like a router."

  if [ "$1" != 'reset' ] && [ "$1" != 'enable' ]; then
    echo "Usage: tb-conf-interface-forwarding [reset|enable] [iface-1] [iface-2]"
    return
  fi

  if [ $1 == 'enable' ] && [ -z $3 ]; then
    echo "Usage: tb-conf-interface-forwarding [reset|enable] [iface-1] [iface-2]"
    return
  fi

  if [ $1 == 'enable' ]; then
    echo "Forwarding packets between $2 and $3"
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo iptables-save > $HOME/.iptables-backup

    sudo iptables -I FORWARD -i $2 -o $3 -j ACCEPT
    sudo iptables -I FORWARD -i $3 -o $2 -j ACCEPT
    sudo iptables -t nat -I POSTROUTING -o $2 -j MASQUERADE
    sudo iptables -t nat -I POSTROUTING -o $3 -j MASQUERADE

  elif [ $1 == 'reset' ]; then
    echo "Reset routing tables to backed up values."
    sudo sysctl -p /etc/sysctl.conf

    sudo iptables-restore $HOME/.iptables-backup
  fi

  echo "Current iptable Configuration"
  sudo sysctl net.ipv4.ip_forward
  sudo iptables -S
  sudo iptables -S -t nat
}

export -f forward_network_interfaces
forward_network_interfaces $1 $2 $3
