version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - ALLOWEDIPS=10.0.0.0/0 #optional
    volumes:
      - $PWD/config:/config
      - /lib/modules:/lib/modules

    network_mode: host
    #ports:
      #- 51820:51820/udp
    #sysctls:
      #- net.ipv4.conf.all.src_valid_mark=1
      
    restart: unless-stopped
